### ISSUE TITLE
Trocar a imagem principal do Banner

### ISSUE THREAD

**Issue by mateusKoppe** [FronteiraTec/site-sacc-2019#20]
A ideia seria utilizar alguma foto da UFFS, precisamos de uma imagem com boa qualidade para ocupar toda a tela na intro do site.

**Comment by otaudopatrick** [comment]
Vou me responsabilizar por esta tarefa,mas acredito que vou encontrar algumas dificuldades em encontrar as imagens adequadas ,então aceito qualquer tipo de auxilio,vou criar uma nova branch que vai ser responsável apenas por esta alteração.

**Comment by otaudopatrick** [comment]
A imagem ja foi solicitada para o setor adequada,apenas estou aguardando o retorno,assim que tiver uma resposta ,ja prossigo com a alteração.
