### ISSUE TITLE
Formulário para login

### ISSUE THREAD

**Issue by mateusKoppe** [FronteiraTec/site-sacc-2019#23]
A proposta do site mudou um pouco, não será mais apenas informativo, agora o usuário poderá fazer login.
Sendo assim precisamos de botões (que são na verdade links), que podem estar no cabeçalho ou onde fique melhor que redicionem o usuário para um tela de login onde ele fará login com as credencias do moodle.
Quanto aos componentes que serão necessários como inputs e forms fiquem a vontade para fazer o que julgar a melhor escolha, caso surja qualquer dúvida ou queira alguma opinião essa issue é para isso. :D

**Comment by otaudopatrick** [comment]
Vou ficar responsável por esta issue.
