### ISSUE TITLE
Redações para sessão sobre

### ISSUE THREAD

**Issue by mateusKoppe** [FronteiraTec/site-sacc-2019#24]
Precisamos de redações para os textos que se referem a:
- [ ] O que é SACC?
- [ ] Por quê ir?
- [ ] Objetivo
- [ ] Para quem?

Sei que fica um pouco difícil tirar essa redação do nada. Seria legal dar uma conferida no formato que eventos semelhantes adotam.
Caso seja necessário (provavelmente vai ser) podem me chamar que eu vou atrás de responsáveis para pedir um pouco mais sobre o texto.

**Comment by JeanCHilger** [comment]
Eu fico responsável por esta.
Se necessário posso pedir pra Rafa as informações necessárias.
